--- 
title: "Mathematical Notes for Machine Learning"
author: "Qiushi Yan"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [references.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: enixam/math-foundations
#description: "This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook."
---

# Preface {-}  

This document aims to cover various mathematical topics relevant to machine learning applications, including linear algebra, multivariate calculus, probability theory, computational learning theory, and optimization (statistics should be in another stand-alone document). 

Here is an short outline of each big part 

...



 




Major references (books, online courses, videos, papers) include:  

- **general**
  - [*Mathematics for Machine Learning*](http://gwthomas.github.io/docs/math4ml.pdf) by Garret Thomas
  - *Mathematics for Machine Learning* [@Deisenroth2020]
  - [*Advanced Data Analysis from an Elementary Point of View*](http://www.stat.cmu.edu/~cshalizi/ADAfaEPoV/) by Cosma Rohilla Shalizi
  
- **Linear Algebra**
  - *Linear Algebra and its Applications* [@lay2006-3]  
  - *Linear Algebra and Optimization for Machine Learning* [@DBLP:books/sp/Aggarwal20]  
  - *Matrix Algebra: Theory, Computations, and Applications in Statistics* [@10.5555/1534802]
  - *Linear Algebra and its Applications* [@strang2006linear]  
  - [*Linear Algebra Review and Reference*](http://cs229.stanford.edu/section/cs229-linalg.pdf) on Stanford's cs229 website   
  - Gilbert Strang. 18.065 Matrix Methods in Data Analysis, Signal Processing, and Machine Learning. Spring 2018. Massachusetts Institute of Technology: MIT OpenCourseWare, https://ocw.mit.edu. License: Creative Commons BY-NC-SA.  
  - N. Johnston. [*Advanced Linear and Matrix Algebra*](http://www.njohnston.ca/publications/advanced-linear-and-matrix-algebra/). Springer International Publishing, 2020.[@johnston2020advanced]
  
- **Multivariate Calculus**
  - *Thomas's Calculus* [@weir2018thomas]
  - Steve Butler. [Multivariate Calculus](https://www.calc3.org/). Lowa State
  
- **Probability Theory**  
  - *Probability for Statistics and Machine Learning: Fundamentals and Advanced Topics* [@10.5555/2028916]
  - *Introduction to Probability* [@blitzstein2019] 
  - *Introduction to Probability* [@bertsekas2008introduction]
  - John Tsitsiklis, and Patrick Jaillet. RES.6-012 Introduction to Probability. Spring 2018. Massachusetts Institute of Technology: MIT OpenCourseWare, https://ocw.mit.edu. License: Creative Commons BY-NC-SA.
  
- **Computational Learning Theory**
  - *Learning from Data* [@10.5555/2207825]


Few comments at the end

- In most parts of this notes, we assume we are working with real matrices. But when this notes say "assuming $A \in \mathbb{R}^{m \times n}$", it does not mean the result or theorem can not be applied to complex matrices. 


The document is generated by the **bookdown** package [@R-bookdown].
