
# Solutions of Linear System Ax = b {#linear-system}

A linear system $A\bar{x} = \bar{b}$ when $\bar{b} \not = \bar{0}$ may behave in any one of three possible ways:

- The system has no solution. This occurs when $\bar{b} \not \in \mathcal{R}(A)$. In such cases we try to find *best fits* that meets certain optimization requirements. For example, to make $\|A\bar{x}  - \bar{b}\|$ as small as possible. Such a solution is called the *best fit*. 

- The system has a single unique solution. This occurs when $\bar{b} \in \mathcal{R}(A)$, and $A$ has linearly independent columns, then there exists an unique linear combination $a_1x_1 + \cdots + a_nx_n = \bar{b}$. In the special case when $A$ is square, the solution is simply $\bar{x} = A^{-1}\bar{b}$ 

- The system has infinitely many solutions. This is the case when $\bar{b} \in \mathcal{R}(A)$ and columns of $A$ are linearly dependent, with *free columns*. Any linear combination of current solutions would still satisfy $A\bar{x} = \bar{b}$. In this case, we want to make $\| \bar{x} \|^2$ as small as possible. This is called the *conciseness criterion*.  

Moreover, suppose $\bar{b} \not \in \mathcal{R}(A)$ which means rows and columns of $A$ are both linearly dependent. There are typically infinite many solutions that have the same optimial value in terms of $\|A\bar{x} - \bar{} \|$

In the first scenario, the linear system is called **inconsistent** because there is no $\bar{x}$ that satisfies each equation in the system. Linear systems in the second and third scenario are called **consistent** because there is at least one solution.  



## Lesat Squares Problems 

```{definition}
the **normal equation** 
$$
A^TA\bar{x} = A^T\bar{b}
$$
```

$$
\begin{aligned}
A^T(\bar{b} - A\hat{\bar{x}}) &= \bar{0}
\end{aligned} \\
A^T\bar{b} - A^TA\hat{\bar{x}} = 0 \\
\hat{\bar{x}} = (A^TA)^{-1}A^T\bar{b}
$$



## Generalized Inverse

### Left and Right Inverse


## Ill-Conditioned Matrices 

### Condition Number


$$
\delta x
$$